version: '3.8'


services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: process_db
    ports:
      - "5433:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5673:5672"
      - "15001:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  processus_client:
    build:
      context: ./processus_client
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db/process_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/
    

  processus_fournisseur:
    build:
      context: ./processus_fournisseur
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db/process_db
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672/

  ui_frontend:
    build: 
      context: ./ui_frontend/ui_frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - processus_client
      - processus_fournisseur
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8085:8080"
    command:
    - start-dev

volumes:
  postgres_data:
